---

- name: Validate filebeat config
  shell: >
    if [[ -f {{ filebeat_bin_dir }}/filebeat.sh ]] ; then
        {{ filebeat_bin_dir }}/filebeat.sh \
        -c {{ filebeat_conf_dir }}/filebeat.yml \
        -e -configtest
    else
        {{ filebeat_bin_dir }}/filebeat test config
    fi

- name: Restart filebeat
  service: name=filebeat state=restarted
